### ISSUE TITLE
Xcode8 beta : Slim Server died 

### ISSUE THREAD

**Issue by Shashikant86** [paulstringer/OCSlimProject#13]
While executing fitness target on Xcode 8 and iOS10 on macOS Sierra. Just wondering if following error is because of beta version Xcode8 Or Apple stopped support for communication of App from server for security reason ?  Error looks like this 

![slim_server_xcode](https://cloud.githubusercontent.com/assets/683799/17307671/3d0a6e40-582e-11e6-9e77-8146105d69f1.png)

**Comment by paulstringer** [comment]
Haven't looked into Xcode 8 yet. This will be related to an old version of ios-sim that's bundled and being used to launch the simulator. There are more recent versions but they rely on node.js and so I'm avoiding it as adding a further dependancy. It will probably be necessary to roll our own simctl wrapper.

**Comment by paulstringer** [comment]
Feel free to branch this and suggest a pull that migrates from ios-sim to instead  xcrun simctl. The place you should be looking for is the script RunSlimTestTargetWithSlimPort which has the call to ios-sim. Any help with this greatly appreciated.

**Comment by paulstringer** [comment]
Other option, update the version of ios-sim and require node.js to be installed but I consider that to be an unnecessary dependancy for the end user.

**Comment by Shashikant86** [comment]
@paulstringer 
Thanks for the suggestions. Just tried  with following 
1] Upgrading 'iso-sim' to latest version 5.0.8 
2] Using xcrun simctl  in the command 

```
             xcrun simctl launch booted $APP_PATH --devicetypeid       "com.apple.CoreSimulator.SimDeviceType.$DEVICE_TYPE, $DEPLOYMENT_TARGET_VALUE" --verbose --args $SLIM_PORT  
```

Now original error has gone but slim port isn't starting :( 

![screen shot 2016-08-16 at 10 40 13 pm](https://cloud.githubusercontent.com/assets/683799/17716982/2cc7f7e2-6403-11e6-9184-2ca64873a345.png)

If you have local setup can you please try it on your end ?
Good thing is original error "failed to find class DTiPhoneSimulator ..... " has disappeared !

**Comment by paulstringer** [comment]
I think simctl handles the passing of args perhaps differently. If using simctl there won't be any need for ios-sim. However ios-sim handles a lot of the complexity of installing the app in the first place. Have you tried using ios-sim to handle the actual launch.

**Comment by Shashikant86** [comment]
@paulstringer I have created [demo project](https://github.com/Shashikant86/XCFit-macOS-Sierra) to test it on Xcode 8 image of TravisCI. Looks like slim server starts but not sure why tests are not detecting. Please refer TavisCI build [here](https://travis-ci.org/Shashikant86/XCFit-macOS-Sierra/builds/155907125) &  raw logs [here](https://s3.amazonaws.com/archive.travis-ci.org/jobs/155907126/log.txt)
Issue related to Xcode8 beta seems relevant to slim error (not sure) 'App launch in simulator" it need Xcode to move to and from 'Application" directory  Issue [here](https://forums.developer.apple.com/thread/48540)

**Comment by paulstringer** [comment]
I'll look into this in the current release I'm preparing and check before releasing to make sure it's compatible with Xcode 8. Probably as simple as just an update to the latest ios-sim that's bundled in as part of OCSlimProject.

**Comment by paulstringer** [comment]
Version 1.3. has now been released which resolves this issue. Check out the README about a known issue with CI systems and running the Simulator. Check out the .travis.yml file in the Release for an example command line build which works correctly under macOS 10.12 and Xcode 8.

https://travis-ci.org/paulstringer/OCSlimProject/builds/158434689
