### ISSUE TITLE
Working with Pods

### ISSUE THREAD

**Issue by crmitchelmore** [paulstringer/OCSlimProject#18]
I'm trying to integrate this in to an existing project so I can experiment with using fitnesse. 

I'm having real trouble getting it to work with other pods frameworks. "No such module" is the most frequent issue. I've tried as many combinations of Podfile and manually setting Framework search paths, build phases and the likes but I can't figure it out. 

I've resorted to using the demo project https://github.com/paulstringer/CosyHome and trying to add a single Pod but still can't seem to get it.

**Comment by crmitchelmore** [comment]
Managed to get it working by building the pods scheme for acceptance tests and adding the frameworks to linked libs. Also having the framework search paths include $(SRCROOT) recursive. Any badly configured pods that use #imports need to be replace with @imports.

**Comment by paulstringer** [comment]
@crmitchelmore thanks for raising and resolving. Interesting issue. Sounds like we should add include $(SRCROOT) recursive to the AcceptanceTest Xcode Template?

**Comment by paulstringer** [comment]
Run a few experiments and things appeared to be reasonably ok. Could you supply a Podfile which reproduces the issue? Thanks.

**Comment by dcutting** [comment]
The current master works out of the box for me on a project with a fairly complicated pod structure.
