### ISSUE TITLE
Fitnesse Test Report Data File Not Found.

### ISSUE THREAD

**Issue by mylegfeelsfunny** [paulstringer/OCSlimProject#19]
I have followed the instructions from the README and added the AcceptanceTests target as dependency to the AcceptanceUnitTests. Then added the AcceptanceUnitTests to the main targets build so that its unit tests are run last to prevent the Xcode 8 error.

But for all tests, it can't seem to locate the Fitnesse-Test-Report.xml while running. 
````
2017-03-30 11:42:36.909 xctest[55495:2103957] [OCSP] ERROR: Could not read data : The file "Fitnesse-Test-Report.xml" couldn’t be opened because there is no such file: Check your 'OCSlimProject' Acceptance Test target is being built. 1) Try running 'pod update' to resolve this issue. 2) Manually run Acceptance Tests using '$ ./LaunchFitnesse' located at your projects root directory and investigate any issues.
Test Suite 'All tests' started at 2017-03-30 11:42:36.911
Test Suite 'AcceptanceUnitTests.xctest' started at 2017-03-30 11:42:36.912
Test Suite 'AcceptanceUnitTests.xctest' passed at 2017-03-30 11:42:36.913.
	 Executed 0 tests, with 0 failures (0 unexpected) in 0.000 (0.000) seconds
Test Suite 'OCSlimProjectTestBundleSupport.framework' started at 2017-03-30 11:42:36.913
Test Suite 'OCSPTestSuite' started at 2017-03-30 11:42:36.914
Test Case '-[OCSPTestSuite TestSuiteReportDataExists]' started.
/Users/****/Pods/OCSlimProjectTestBundleSupport/Pod/TestClasses/OCSPAssertRecorder.m:7: error: -[OCSPTestSuite TestSuiteReportDataExists] : failed - Fitnesse Test Report Data File Not Found. Check log files for possible [OCSP] warnings or errors.
Test Case '-[OCSPTestSuite TestSuiteReportDataExists]' failed (0.001 seconds).
Test Case '-[OCSPTestSuite tearDown]' started.
Test Case '-[OCSPTestSuite tearDown]' passed (0.000 seconds).
Test Suite 'OCSPTestSuite' failed at 2017-03-30 11:42:36.917.
	 Executed 2 tests, with 1 failure (0 unexpected) in 0.002 (0.003) seconds
Test Suite 'OCSlimProjectTestBundleSupport.framework' failed at 2017-03-30 11:42:36.917.
	 Executed 2 tests, with 1 failure (0 unexpected) in 0.002 (0.004) seconds
Test Suite 'All tests' failed at 2017-03-30 11:42:36.917.
	 Executed 2 tests, with 1 failure (0 unexpected) in 0.002 (0.006) seconds

````

The kicker is, I see the xml file in the AcceptanceUnitTests.test bundle.

`ERROR: Could not read data : The file "Fitnesse-Test-Report.xml" couldn’t be opened because there is no such file: Check your 'OCSlimProject' Acceptance Test target is being built. 1) Try running 'pod update' to resolve this issue. 2) Manually run Acceptance Tests using '$ ./LaunchFitnesse' located at your projects root directory and investigate any issues.`

Does not resolve anything, and the tests work when launched from the command line.

Is there a path I need to update so the Unit Tests can find it?

**Comment by mylegfeelsfunny** [comment]
Looks as though the unit test bundle is resolving to this location

`/Build/Products/Debug-iphonesimulator/AcceptanceUnitTests.xctest/Frameworks/OCSlimProjectTestBundleSupport.frame
work/`

when the xml is being saved to 

`/Build/Products/Debug-iphonesimulator/AcceptanceUnitTests.xctest/`

I can get it to run by changing the `OCSP_TEST_REPORT_FILE_PATH`

**Comment by paulstringer** [comment]
Thanks for the detailed report. Looking at it.

**Comment by paulstringer** [comment]
This likely could result when using the `pod install --no-integrate` feature. The result of this is Build Settings specified by the Pod for the target are not set. 

To resolve this just simply add the following to your Acceptance Unit Test Target's Build Settings.

PODS_ROOT = ${SRCROOT}/Pods
OCSP_SUPPORT_FILE_DIR=${PODS_ROOT}/OCSlimProject/Pod/Support/SharedSupport
OCSP_TEST_REPORT_FILE_NAME = Fitnesse-Test-Report.xml
OCSP_TEST_REPORT_FILE_PATH = ${TARGET_BUILD_DIR}/${EXECUTABLE_FOLDER_PATH}/${OCSP_TEST_REPORT_FILE_NAME}

**Comment by paulstringer** [comment]
Closing this issue - The noted solution should be tried if encountering similar problems. Additional issues if this reoccurs welcome. 👍
