### ISSUE TITLE
Fixture name in table doesn't resolve to a class unless there are spaces in the name

### ISSUE THREAD

**Issue by dcutting** [paulstringer/OCSlimProject#20]
I have a table like this:

```
|FixtureLandmarkService   |
|name  |latitude|longitude|
|London|51.5    |0.1      |
|Paris |48.8    |2.3      |
```
I have a fixture class named `FixtureLandmarkService`.

When I run the test I get an exception:

> Could not find class FixtureLandmarkService<a

Note the `<a` at the end of the warning - that's probably a clue to how the class name mangler is failing.

When I change the table to the following, it works fine:

```
|Fixture Landmark Service |
|name  |latitude|longitude|
|London|51.5    |0.1      |
|Paris |48.8    |2.3      |
```

Note the spaces in the fixture declaration.

**Comment by paulstringer** [comment]
The second style using spaces in the declaration is preferred and probably considered _correct_. 

The problem you've encountered is that the Camel Case declaration matches the criteria for a [WikiWord](http://fitnesse.org/FitNesse.FullReferenceGuide.UserGuide.FitNesseWiki.WikiWord). 

When Fitnesse detects a Wiki Word it's behind the scenes rendering it to an <a></a> link and passing this to the Slim interpreter. 

It would be better if Fitnesse were able to gracefully detect this easy mistake within the context of a table and this probably is best directed at the [Fitnesse project](https://github.com/unclebob/fitnesse)

If you prefer to use CamelCase for table names you can still do so by marking it up so it ignores WikiWords using the following markup

`!-FixtureLandmarkService-!`
